version: "3"
services:
  client:
    build:
      context: .
      dockerfile: js.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000
      - 35729:35729
  server:
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./server:/server
