version: "3"
services:
  client:
    build:
      context: .
      dockerfile: js.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      - db
      - client

  db:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - 5432:5432
