version: "3"
services:
  client:
    build:
      context: .
      dockerfile: js.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000

  server:
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 5000:5000