version: "3"
services:
  app:
    build:
      context: .
      dockerfile: js.Dockerfile
    volumes:
        - ./app:/app
        - /app/node_modules

  web:
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
        - ./web:/web
    